name: CI

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Download Visual Studio
        run: Invoke-WebRequest https://download.visualstudio.microsoft.com/download/pr/982db8b2-559c-4282-a026-c19b78f8d7ae/5ea5f5ec5eb5fdaf8e7a09aa6c956b6eb1f6c5c6d5e5b5d5e17d5e9f6d5c5f5e/en_visual_studio_community_2022_rc_web_Installer.exe -OutFile vs_community.exe
      - name: Install Visual Studio
        run: .\vs_community.exe --installPath "C:\Program Files (x86)\Microsoft Visual Studio\2022\Community" --quiet --wait --norestart
        shell: cmd
      - name: Download ngrok
        run: Invoke-WebRequest https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-windows-amd64.zip -OutFile ngrok.zip
      - name: Extract ngrok
        run: Expand-Archive ngrok.zip
      - name: Authenticate ngrok
        run: .\ngrok\ngrok.exe authtoken $Env:NGROK_AUTH_TOKEN
        env:
          NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
      - name: Enable Remote Desktop
        run: |
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-name "fDenyTSConnections" -Value 0
          Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
          Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText "P@ssw0rd!" -Force)
      - name: Create ngrok TCP tunnel
        run: .\ngrok\ngrok.exe tcp 3389
